
package visual;
import javax.swing.table.*;
import java.util.ArrayList;
import java.util.Map.*;
import billsplitter.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class conta extends javax.swing.JFrame {
    Utilizador u;
    Casa c;
    ArrayList<Despesa> despesasPagas;
    ArrayList<Despesa> despesasPorPagar;
    public conta(String email) {
        BillSplitter bs=new BillSplitter();
        u=bs.getUser(email);
        c=bs.getCasa(u.getCasa());
        initComponents();
        jsaldo.setText(String.valueOf(u.getSaldo()));
        
        DefaultTableModel modelT1= (DefaultTableModel)tabela1.getModel();
        despesasPagas=new ArrayList<Despesa>();
        despesasPorPagar=new ArrayList<Despesa>();
        for(Despesa d : new DAODespesa().getDespesasCasa(c.getId()) )
            if(d.getEstado()==false)
                despesasPorPagar.add(d);
            else despesasPagas.add(d);
        
        for(Despesa d : despesasPorPagar)
            modelT1.insertRow(modelT1.getRowCount(), new Object []{d.getDescricao(),d.getMontante(),d.getData_limite()});
        
        DefaultTableModel modelT2= (DefaultTableModel)tabela2.getModel();
        for(Entry<String,Float> e : u.getSituacoesIrregulares().entrySet()){
            modelT2.insertRow(modelT2.getRowCount(), new Object []{e.getKey(),e.getValue().toString()});
        }
        
        tabela1.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
            for(Despesa d : despesasPorPagar)
                if(d.getDescricao().equals(tabela1.getValueAt(tabela1.getSelectedRow(), 0))){
                    new despesas(email,d).setVisible(true);
                    setVisible(false);
                }
        }});
        
        tabela2.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
            new transferir(email,(String)tabela2.getValueAt(tabela2.getSelectedRow(), 0)).setVisible(true);
            setVisible(false);
                
        }});
        
        jsair.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e){
                new home().setVisible(true);
                setVisible(false);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jsair = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();
        jadd_despesa = new javax.swing.JButton();
        jdesp_recorrentes = new javax.swing.JButton();
        jdesp_liquidadas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jsaldo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jdel_morador = new javax.swing.JButton();
        jedit_conta = new javax.swing.JButton();
        add_morador = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela2 = new javax.swing.JTable();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("BillSplitter");

        jsair.setText("Sair");

        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Valor", "Data Limite"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela1);

        jadd_despesa.setText("Adicionar Despesa");
        jadd_despesa.setToolTipText("");
        jadd_despesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadd_despesaActionPerformed(evt);
            }
        });

        jdesp_recorrentes.setText("Gerir Despesa Recorrente");
        jdesp_recorrentes.setToolTipText("");
        jdesp_recorrentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdesp_recorrentesActionPerformed(evt);
            }
        });

        jdesp_liquidadas.setText("Despesas Liquidadas");
        jdesp_liquidadas.setToolTipText("");
        jdesp_liquidadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdesp_liquidadasActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Conta Corrente:");

        jsaldo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        jLabel5.setText("Compromissos com:");

        jdel_morador.setText("Remover Morador");
        jdel_morador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdel_moradorActionPerformed(evt);
            }
        });

        jedit_conta.setText("Editar Conta");
        jedit_conta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jedit_contaActionPerformed(evt);
            }
        });

        add_morador.setText("Adicionar Morador");
        add_morador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_moradorActionPerformed(evt);
            }
        });

        tabela2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Morador", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabela2);
        if (tabela2.getColumnModel().getColumnCount() > 0) {
            tabela2.getColumnModel().getColumn(0).setResizable(false);
            tabela2.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jadd_despesa, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jdesp_recorrentes, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(465, 465, 465))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(add_morador, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jdesp_liquidadas, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jsaldo))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jdel_morador, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jedit_conta, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(461, 461, 461)
                        .addComponent(jsair, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsair, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jsaldo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdesp_liquidadas, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(add_morador, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jdel_morador, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jedit_conta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jadd_despesa, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdesp_recorrentes, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jadd_despesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadd_despesaActionPerformed
        new adicionar_despesa(u.getEmail()).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jadd_despesaActionPerformed

    private void jdesp_recorrentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdesp_recorrentesActionPerformed
        new despesas_recorrentes(u.getEmail()).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jdesp_recorrentesActionPerformed

    private void jdesp_liquidadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdesp_liquidadasActionPerformed
        if(jdesp_liquidadas.getText().equals("Despesas Liquidadas"))
            jdesp_liquidadas.setText("Despesas por liquidar");
        else jdesp_liquidadas.setText("Despesas Liquidadas");
        
    }//GEN-LAST:event_jdesp_liquidadasActionPerformed

    private void jdel_moradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdel_moradorActionPerformed
        new remover_morador(u.getEmail()).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jdel_moradorActionPerformed

    private void jedit_contaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jedit_contaActionPerformed
        new editar_conta(u).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jedit_contaActionPerformed

    private void add_moradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_moradorActionPerformed
        new adicionar_morador(u.getEmail()).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_add_moradorActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conta("email").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_morador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jadd_despesa;
    private javax.swing.JButton jdel_morador;
    private javax.swing.JButton jdesp_liquidadas;
    private javax.swing.JButton jdesp_recorrentes;
    private javax.swing.JButton jedit_conta;
    private javax.swing.JLabel jsair;
    private javax.swing.JLabel jsaldo;
    private javax.swing.JTable tabela1;
    private javax.swing.JTable tabela2;
    // End of variables declaration//GEN-END:variables
}
