python3 main.py -i barreto/coordChrist50.dat -o barreto/coordChrist50.json
python3 main.py -i barreto/coordGaspelle.dat -o barreto/coordGaspelle.json
python3 main.py -i barreto/coordChrist100.dat -o barreto/coordChrist100.json
python3 main.py -i barreto/coordDas88.dat -o barreto/coordDas88.json
python3 main.py -i barreto/coordMin27.dat -o barreto/coordMin27.json
python3 main.py -i barreto/coordOr117.dat -o barreto/coordOr117.json
python3 main.py -i barreto/coordGaspelle6.dat -o barreto/coordGaspelle6.json
python3 main.py -i barreto/coordMin134.dat -o barreto/coordMin134.json
python3 main.py -i barreto/coordChrist75.dat -o barreto/coordChrist75.json
python3 main.py -i barreto/coordGaspelle5.dat -o barreto/coordGaspelle5.json
python3 main.py -i barreto/coordDas150.dat -o barreto/coordDas150.json
python3 main.py -i barreto/coordGaspelle4.dat -o barreto/coordGaspelle4.json
python3 main.py -i barreto/coordGaspelle3.dat -o barreto/coordGaspelle3.json
python3 main.py -i barreto/coordGaspelle2.dat -o barreto/coordGaspelle2.json
